CREATE TABLE IF NOT EXISTS rooms (
  room_code             TEXT PRIMARY KEY,
  owner_socket_id       TEXT NOT NULL,
  owner_client_id       TEXT,
  audio_socket_id       TEXT,
  audio_client_id       TEXT,
  playlist_name         TEXT NOT NULL,
  created_by            TEXT NOT NULL,
  current_song_id       TEXT,
  current_source        TEXT,
  is_playing            BOOLEAN NOT NULL DEFAULT false,
  current_position      NUMERIC NOT NULL DEFAULT 0,
  volume                INTEGER NOT NULL DEFAULT 100,
  announcement_enabled  BOOLEAN NOT NULL DEFAULT false,
  default_index         INTEGER NOT NULL DEFAULT 0,
  host_id               UUID REFERENCES users(id) ON DELETE SET NULL,
  tier                  TEXT NOT NULL DEFAULT 'free',
  status                TEXT NOT NULL DEFAULT 'active',
  expires_at            TIMESTAMPTZ,
  ended_at              TIMESTAMPTZ,
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  updated_at            TIMESTAMPTZ DEFAULT NOW(),
  last_activity         TIMESTAMPTZ DEFAULT NOW()
);
